[features]
reverse_proxy_authentication = true
oauth_server = true

[frontend.metadata]
instance_hostname = "127.0.0.1:4080"
alias = "Example configuration"
public_description = "This server supports OAuth authentication, accepts emails ending in @example.com"
image = "https://images.unsplash.com/photo-1739609579483-00b49437cc45?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
background_colour = "#0b040e"
domain_placeholder="example.com"
username_placeholder="username"
acess_denied_header=""

[authentication_methods.microsoft_entra]
active = true
method_type = "oauth"
applied_policies = ["staff_only"]
login_page = "https://login.microsoftonline.com/[YOUR LOGIN URL]"
alias = "Microsoft"
icon = "https://www.microsoft.com/favicon.ico?v2"
oauth_client_api = "https://graph.microsoft.com/"
oauth_client_user_info = "https://graph.microsoft.com/oidc/userinfo"
oauth_client_user_info_id = "sub"
oauth_client_token_endpoint = "https://login.microsoftonline.com/680e4b74-1b4d-4565-9a12-3a6c94c91a52/oauth2/v2.0/token"
oauth_client_token_endpoint_redirect_uri = "https://127.0.0.1:8000/frontend/magiclink?authentication_method=microsoft_entra"
oauth_client_scope = "openid profile email"
oauth_client_id = "[YOUR_OAUTH_CLIENTID]"
oauth_client_secret_env = "[YOUR_OAUTH_SECRET]"

[policies.staff_only]
active = true
action = "allow"
property = "email"
ends_with = "@example.com"

[hostname.anythingyouwant]
active = true
host = "myawesomewebsite.example.com"
applied_policies = ["specific_users"]
authentication_methods = ["email"]
multistep_authentication_methods = false