stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

# This job checks out the repository and builds the Docker image
build:
  image: rust:latest
  stage: build
  services:
    - docker:dind
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
  artifacts:
    paths:
      - /builds/oracularhades/guard/target/release/guard-server

release_job:
  stage: push
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Running release_job for $TAG"
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file /builds/oracularhades/guard/target/release/guard-server \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/guard-server/$CI_COMMIT_SHORT_SHA/guard-server"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: $CI_COMMIT_SHORT_SHA
    assets:
      links:
        - name: 'asset2'
          url: '$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/guard-server/$CI_COMMIT_SHORT_SHA/guard-server'  # Updated to point to GitLab Packages
          filepath: '/builds/oracularhades/guard/target/release/guard-server'
          link_type: 'other' # optional