stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

# This job checks out the repository and builds the Docker image
build:
  image: rust:latest
  stage: build
  services:
    - docker:dind
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

release_job:
  stages:
    - build
    - push
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: 'latest'                                                 # variables must be defined elsewhere
    assets:
      links:
        - name: 'asset2'
          filepath: '/target/release/guard-server' # optional
          link_type: 'other' # optional