stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

# This job checks out the repository and builds the Docker image
build:
  image: rust:latest
  stage: build
  services:
    - docker:dind
  script:
    - rustc --version && cargo --version  # For any future debugging.
    - cargo build --verbose --release
    - cargo test --verbose
    - mkdir release
    - mv /builds/oracularhades/guard/target/release/guard-server /builds/oracularhades/release
  artifacts:
    paths:
      - /builds/oracularhades/release