stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

# This job checks out the repository and builds the Docker image
build:
  image: rust:latest
  stage: build
  services:
    - docker:dind
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
  artifacts:
    paths:
      - /builds/oracularhades/guard/target/release/guard-server