[package]
name = "guard_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.20"
rocket = { version = "0.5.1", features = ["json"] }
url = "2.5.0"
serde = "1.0.196"
serde_json = "1.0.117"

[lib]
name = "guard_auth"
path = "src/lib.rs"
