name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'latest'
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: install tree
      run: sudo apt-get install tree
    - name: mkdir guard
      run: mkdir guard
    - name: npm install && npm run build
      run: npm install && npm run build
    - name: Run tree
      run: tree
    - name: Move files.
      run: mv ./frontend/_static ./guard/frontend/_static && mv ./admin-panel ./guard
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: Release ${{ github.ref_name }}
        files: |
          ./guard
