name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Set homebrew
      run: export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
    - name: install tree
      run: sudo apt-get install tree default-mysql-server default-libmysqlclient-dev && NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew install mysql
    - name: mkdir guard
      run: mkdir guard
    - name: cd frontend && npm install && npm run build && cd ..
      run: cd frontend && npm install && npm run build && cd ..
    - name: Run tree
      run: tree
    - name: Move files.
      run: mkdir ./guard/frontend && mv ./frontend/_static ./guard/frontend/_static && mv ./target/release/* ./guard/
    - name: Zip output folder.
      run: zip -r guard.zip ./guard
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: Release ${{ github.ref_name }}
        files: |
          ./guard.zip
